services:
  db:
    image: postgres:16.8
    ports:
      - "5434:5432"
    restart: always
    # If we accidentally kill the running container, Docker Compose
    # will restart it.

    # The PostgreSQL Docker container uses environment variables to
    # read configuration, here we set the password.
    # ⚠️ - Do no store plaintext passwords in source control. We
    #      do so here as this is a tutorial.
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_PORT: 5434
      POSTGRES_USER: postgres
      POSTGRES_DB: risk-management
      

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

